
default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: user_postgres_template_development

  
test:
  <<: *default
  database: user_postgres_template_test


production:
  <<: *default
  database: user_postgres_template_production
  username: ubuntu
  password: <%= ENV['USER_POSTGRES_TEMPLATE_DATABASE_PASSWORD'] %>
