default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blackbelt3_development

 
test:
  <<: *default
  database: blackbelt3_test


production:
  <<: *default
  database: blackbelt3_production
  username: ubuntu
  password: <%= ENV['BLACKBELT3_DATABASE_PASSWORD'] %>
