# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4585c1bbfa61c3be5432e395b014db77ee8a17c2d1e51e5d86a1fe3ae1501d2b2dca33c24b0defc7478c87d5e4fa3c0e4b8920e9f8806678a65c1579af07a6bf

test:
  secret_key_base: 786e869efbf4ae4cdccc6ca7970ea731a8925b6d450949dd346d227d9c3a2d166286039f2a7fbcf51ea4937998ed64cd15a00351e6e96542fab1365f8548f72d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
